server:
  port: 8080

spring:
  application:
    name: boot-admin

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf-8&isSSL=false
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:mapper/**

logging:
  level:
    org.springframework.security: trace
    com.boot.admin.infra.repository: debug